#!/usr/bin/env bash
# archive_pointer_test.sh — E-245 (D-066 §5): rotated history stays findable.
#
# `archive_done_tasks` moves DONE rows beyond the last ten into
# .ai/archive/state-done-YYYY-MM.json. In this repository that took TASKS.md from 261
# lines to 25 — the right trade, and the reason the rotation exists. What it left behind
# was a view showing ten completed tasks and NO INDICATION that 117 more existed or where
# they went. History nobody can find has been lost as far as the next reader is concerned.
#
# THE POINTER MUST SURVIVE A REGENERATION, which is the whole difficulty: TASKS.md is a
# generated view with TWO projectors (state-db.js regenerateViews, state-writer.js
# regenerateMarkdown) that duplicate its layout line for line. A pointer emitted by only
# one of them disappears the next time the other runs — so both are asserted here, and
# both call one shared helper.
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/assert.sh"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DB="${REPO_ROOT}/src/mcp/shared/state-db.js"

echo "── Suite: archive_pointer_test (E-245) ─────────────────────────────"

_ai() {  # <archive-filenames...> → an .ai dir with those archive files
  local d; d="$(test_tmpdir e245)"
  mkdir -p "$d/archive"
  local f; for f in "$@"; do printf '{"tasks":[]}' > "$d/archive/$f"; done
  printf '%s' "$d"
}
_pointer() { node --input-type=module -e "
  const { archivePointerLines } = await import('file://${DB}');
  process.stdout.write(archivePointerLines('$1').join('\n'));
" 2>/dev/null; }

# ── E-245.1: the pointer names every archive file, sorted ────────────────────
_a="$(_ai state-done-2026-09.json state-done-2026-05.json state-done-2026-06.json)"
_out="$(_pointer "$_a")"
assert_contains "E-245.01a: the section is headed" "## Archived" "$_out"
assert_contains "E-245.01b: an archive file is named with its path" \
  '`.ai/archive/state-done-2026-05.json`' "$_out"
assert_contains "E-245.01c: and so is every other one" \
  '`.ai/archive/state-done-2026-09.json`' "$_out"
# Chronological order, not readdir order: the list is read by a person looking for a date.
_first="$(printf '%s\n' "$_out" | grep 'state-done' | head -1)"
assert_contains "E-245.01d: files are listed in sorted order, not filesystem order" \
  "2026-05" "$_first"
# The narrative lives in LOG.md; a pointer to the JSON alone sends the reader to a file
# that answers 'what' and not 'why'.
assert_contains "E-245.01e: it points at LOG.md for the narrative" "LOG.md" "$_out"

# ── E-245.2: nothing is emitted when there is nothing to point at ────────────
# A project that has never rotated must not grow a phantom section.
_empty="$(_ai)"
_eout="$(_pointer "$_empty")"
assert_status 0 "E-245.02a: no archive files → no section at all" \
  bash -c "[[ -z '$_eout' ]]"
# An .ai/ with no archive DIRECTORY at all is the fresh-project case and must not throw.
_noarch="$(test_tmpdir e245bare)"
assert_status 0 "E-245.02b: a missing archive/ directory is not an error" \
  bash -c "node --input-type=module -e \"
    const { archivePointerLines } = await import('file://${DB}');
    archivePointerLines('$_noarch');
  \" >/dev/null 2>&1"
# Only the DONE-task archives — stamps rotate into the same directory and are not tasks.
_mixed="$(_ai state-done-2026-09.json stamps-2026-09.json)"
_mout="$(_pointer "$_mixed")"
assert_status 1 "E-245.02c: a stamps archive is not listed as task history" \
  bash -c "printf '%s' '$_mout' | grep -q 'stamps-2026-09'"
assert_contains "E-245.02d: while the task archive beside it still is" \
  'state-done-2026-09.json' "$_mout"

# ── E-245.3: BOTH projectors emit it ─────────────────────────────────────────
# The property that actually keeps the pointer alive. TASKS.md is regenerated by two
# functions in two files; whichever runs last wins, so one that omits the pointer silently
# deletes it.
assert_status 0 "E-245.03a: state-db.js regenerateViews emits the pointer" \
  bash -c "sed -n '/^export function regenerateViews/,/^}/p' '$DB' | grep -q 'archivePointerLines(aiDir)'"
assert_status 0 "E-245.03b: state-writer.js regenerateMarkdown emits it too" \
  bash -c "sed -n '/^export function regenerateMarkdown/,/^}/p' '${REPO_ROOT}/src/mcp/shared/state-writer.js' | grep -q 'archivePointerLines(aiDir)'"
# ONE implementation, imported — not two copies that can drift apart the way the rest of
# the TASKS.md layout already has.
assert_status 0 "E-245.03c: state-writer imports the helper rather than copying it" \
  grep -q 'archivePointerLines } from "./state-db.js"' "${REPO_ROOT}/src/mcp/shared/state-writer.js"

# ── E-245.4: the hygiene items ───────────────────────────────────────────────
assert_status 1 "E-245.04a: the stray root file 'bash' is no longer tracked" \
  bash -c "cd '$REPO_ROOT' && git ls-files --error-unmatch bash >/dev/null 2>&1"
assert_status 0 "E-245.04b: .DS_Store is gitignored at every depth" \
  bash -c "grep -qx '\*\*/.DS_Store' '${REPO_ROOT}/.gitignore'"
assert_status 1 "E-245.04c: and no .DS_Store is tracked" \
  bash -c "cd '$REPO_ROOT' && git ls-files | grep -q 'DS_Store'"
assert_status 0 "E-245.04d: the testsprite scratch dir is ignored" \
  bash -c "grep -q 'testsprite_tests/tmp/' '${REPO_ROOT}/.gitignore'"
# The live view carries the pointer WHEN THIS CHECKOUT HAS AN ARCHIVE. It usually does not:
# .ai/archive/ is untracked, so a CI checkout has no archive files at all — and the
# projector is then CORRECT to emit no section. Asserting unconditionally made this test
# depend on whether a directory survived the clone; it passed locally and failed on CI, the
# exact environment dependence E-236 exists to remove, written into the suite that adds the
# feature. Gated on the evidence the pointer is derived from.
if compgen -G "${REPO_ROOT}/.ai/archive/state-done-*.json" >/dev/null 2>&1; then
  assert_status 0 "E-245.04e: this repo's own TASKS.md carries the pointer" \
    grep -q '^## Archived' "${REPO_ROOT}/.ai/TASKS.md"
else
  _skip "E-245.04e: this checkout has no .ai/archive/ — nothing for the view to point at"
fi

echo ""
assert_summary
if [[ "${FAIL_COUNT:-0}" -eq 0 ]]; then
  echo "===== archive_pointer_test.sh PASS ====="
else
  echo "===== archive_pointer_test.sh FAIL (${FAIL_COUNT}) ====="
fi
