#!/usr/bin/env bash
# mcp_doc_sync_test.sh — Tests for E-52 MCP Registry Auto-Generation.
#
# Verifies the contract demanded by drift-resolution-2026.md
# §"Auto-Generated Documentation":
#   • scripts/generate_mcp_docs.mjs exists and emits deterministic output.
#   • The committed .ai/blueprints/mcp.md is byte-identical to a fresh
#     generator run — i.e. nobody hand-edited it (CI gate).
#   • src/mcp/shared/mcp-domains.mjs is the single DOMAINS source shared
#     with mcp-router (no duplicated map).
#   • bin/ai do_sync() invokes _regenerate_mcp_docs.
#   • install-ai-os.sh ships scripts/ to ~/.ai-os/scripts/ so downstream
#     projects can regenerate too.
#   • Generator is fail-open: a malformed registry warns but exits 0.

set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/assert.sh"

REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
GEN="${REPO_ROOT}/scripts/generate_mcp_docs.mjs"
DOMAINS_MJS="${REPO_ROOT}/src/mcp/shared/mcp-domains.mjs"
MCP_MD="${REPO_ROOT}/.ai/blueprints/mcp.md"
BIN_AI="${REPO_ROOT}/src/bin/ai"
INSTALLER="${REPO_ROOT}/install-ai-os.sh"

echo "===== mcp_doc_sync_test.sh ====="

# ── T-MCPDOC-S01: generator + DOMAINS source exist ───────────────────────────
echo ""
echo "  [T-MCPDOC-S01] generator + DOMAINS source files present"

assert_status 0 "scripts/generate_mcp_docs.mjs exists"  test -f "$GEN"
assert_status 0 "src/mcp/shared/mcp-domains.mjs exists" test -f "$DOMAINS_MJS"
assert_status 0 "DOMAINS exported from shared module" \
  grep -qE 'export const DOMAINS' "$DOMAINS_MJS"

# Single source of truth — mcp-router imports DOMAINS from the shared module
# rather than declaring its own copy.
assert_status 0 "mcp-router imports from shared mcp-domains" \
  grep -qE 'from "\.\./shared/mcp-domains\.mjs"' "${REPO_ROOT}/src/mcp/mcp-router/index.js"

assert_status 1 "mcp-router does NOT redeclare DOMAINS locally" \
  grep -qE '^const DOMAINS = \{' "${REPO_ROOT}/src/mcp/mcp-router/index.js"

# ── T-MCPDOC-S02: committed mcp.md is in sync with generator output ──────────
echo ""
echo "  [T-MCPDOC-S02] mcp.md byte-identical to generator output (CI gate)"

# Regenerate to a temp file so subsequent assertions can grep it directly.
TMP_OUT="$(mktemp)"
node "$GEN" --check > "$TMP_OUT" 2>/dev/null

assert_status 0 "generator output matches committed .ai/blueprints/mcp.md" \
  diff -q "$TMP_OUT" "$MCP_MD"

# Generator output sanity: header marker and expected domains.
assert_status 0 "output carries the AUTO-GENERATED marker" \
  grep -qE 'AUTO-GENERATED by scripts/generate_mcp_docs\.mjs' "$TMP_OUT"

assert_status 0 "output includes the State domain heading" \
  grep -qE '^## State$' "$TMP_OUT"

assert_status 0 "output places mcp-router under Routing & Misc" \
  bash -c "grep -A2 'Routing & Misc' '$TMP_OUT' | grep -q 'mcp-router'"

rm -f "$TMP_OUT"

# ── T-MCPDOC-S03: bin/ai do_sync() invokes the regenerator ──────────────────
echo ""
echo "  [T-MCPDOC-S03] bin/ai wires _regenerate_mcp_docs into do_sync()"

assert_status 0 "bin/ai defines _regenerate_mcp_docs()" \
  grep -qE '^_regenerate_mcp_docs\(\)' "$BIN_AI"

assert_status 0 "do_sync() body invokes _regenerate_mcp_docs" \
  python3 -c "
import re,sys
src=open('${BIN_AI}').read()
m=re.search(r'^do_sync\(\)\s*\{(.*?)^\}', src, re.S|re.M)
sys.exit(0 if m and '_regenerate_mcp_docs' in m.group(1) else 1)
"

# Helper must guard on `node` availability (fail-open).
assert_status 0 "_regenerate_mcp_docs guards on node availability" \
  grep -qE 'command -v node' "$BIN_AI"

# Helper locates the generator from both repo and installed roots.
assert_status 0 "helper falls back to ~/.ai-os/scripts/" \
  grep -qE '\$\{AIOS\}/scripts/generate_mcp_docs\.mjs' "$BIN_AI"

# ── T-MCPDOC-S04: install-ai-os.sh ships scripts/ ────────────────────────────
echo ""
echo "  [T-MCPDOC-S04] install-ai-os.sh ships scripts/ to ~/.ai-os/scripts/"

assert_status 0 "installer copies scripts/ in rsync branch" \
  grep -qE 'rsync .*\$\{REPO_DIR\}/scripts/' "$INSTALLER"

assert_status 0 "installer copies scripts/ in cp fallback branch" \
  grep -qE 'cp -rf "\$\{REPO_DIR\}/scripts/' "$INSTALLER"

# ── T-MCPDOC-S05: fail-open behaviour on broken registry ────────────────────
echo ""
echo "  [T-MCPDOC-S05] generator fail-open against malformed registry"

SBOX="$(mktemp -d)"
mkdir -p "$SBOX/.ai/blueprints" "$SBOX/src/config"
echo '{ this is not json' > "$SBOX/src/config/registry.json"

# Run generator in a subshell with CWD set to the sandbox. The script's
# locator will resolve the local registry first and hit a parse error;
# the parse error path must exit 0 (fail-open) so `ai sync` continues.
EXIT_CODE=0
( cd "$SBOX" && node "$GEN" >/dev/null 2>&1 ) || EXIT_CODE=$?
assert_status 0 "generator exits 0 on malformed registry (fail-open)" \
  test "$EXIT_CODE" -eq 0

rm -rf "$SBOX"

# ── T-MCPDOC-S06: --check mode is read-only ─────────────────────────────────
echo ""
echo "  [T-MCPDOC-S06] --check mode does not modify mcp.md"

MCP_MTIME_BEFORE=$(stat -f %m "$MCP_MD" 2>/dev/null || stat -c %Y "$MCP_MD" 2>/dev/null)
node "$GEN" --check >/dev/null 2>&1
MCP_MTIME_AFTER=$(stat -f %m "$MCP_MD" 2>/dev/null || stat -c %Y "$MCP_MD" 2>/dev/null)
assert_status 0 "mcp.md mtime unchanged after --check run" \
  test "$MCP_MTIME_BEFORE" = "$MCP_MTIME_AFTER"

echo ""
assert_summary
echo "===== mcp_doc_sync_test.sh DONE ====="
