#!/usr/bin/env node
/**
 * generate_mcp_docs.js — auto-generates .ai/blueprints/mcp.md (E-52).
 *
 * Reads src/config/registry.json and groups servers by domain (per
 * src/mcp/shared/mcp-domains.mjs), then emits a deterministic Markdown
 * snapshot at .ai/blueprints/mcp.md.
 *
 * Modes:
 *   node scripts/generate_mcp_docs.mjs          → write .ai/blueprints/mcp.md
 *   node scripts/generate_mcp_docs.mjs --check  → print to stdout, exit 0;
 *                                                used by tests/suites/
 *                                                mcp_doc_sync_test.sh to diff
 *                                                against the committed file.
 *
 * Security:
 *   - All paths are derived from the project root (CWD when invoked from
 *     repo top, or the directory containing src/config/registry.json
 *     discovered by walking upward). No path argument is accepted.
 *   - Fail-open: any read/parse error logs a warning to stderr and exits 0
 *     so an `ai sync` cycle is not blocked by a malformed registry.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

// Domain map import is locator-aware: in the source repo we import the
// in-tree module; in installed mode (~/.ai-os/scripts/) we fall back to the
// installed copy at ~/.ai-os/shared/mcp-domains.mjs. Resolved at runtime.
const SCRIPT_PATH = fileURLToPath(import.meta.url);
const SCRIPT_DIR = dirname(SCRIPT_PATH);

const DOMAINS_CANDIDATES = [
  // Repo development: scripts/ → ../src/mcp/shared/mcp-domains.mjs
  resolve(SCRIPT_DIR, "../src/mcp/shared/mcp-domains.mjs"),
  // Installed mode: ~/.ai-os/scripts/ → ../mcp/shared/mcp-domains.mjs
  resolve(SCRIPT_DIR, "../mcp/shared/mcp-domains.mjs"),
  // Final fallback: explicit ~/.ai-os install root.
  resolve(homedir(), ".ai-os/mcp/shared/mcp-domains.mjs"),
];
let DOMAINS = null;
for (const candidate of DOMAINS_CANDIDATES) {
  if (existsSync(candidate)) {
    DOMAINS = (await import(candidate)).DOMAINS;
    break;
  }
}
if (!DOMAINS) {
  process.stderr.write(
    `[generate_mcp_docs] WARN: mcp-domains.mjs not found in any of ${DOMAINS_CANDIDATES.join(", ")}\n`
  );
  process.exit(0);
}

// Project root: the directory `ai sync` was invoked from. Output goes to
// <project>/.ai/blueprints/mcp.md. If CWD has no .ai/ we no-op.
const PROJECT_ROOT = process.cwd();
const TARGET = join(PROJECT_ROOT, ".ai", "blueprints", "mcp.md");

// Registry locator: prefer the project's in-tree copy (the AI-OS repo itself),
// fall back to the global install (~/.ai-os/config/registry.json) for any
// downstream project that runs `ai sync`.
const REGISTRY_CANDIDATES = [
  join(PROJECT_ROOT, "src", "config", "registry.json"),
  join(homedir(), ".ai-os", "config", "registry.json"),
];
let REGISTRY = null;
for (const candidate of REGISTRY_CANDIDATES) {
  if (existsSync(candidate)) {
    REGISTRY = candidate;
    break;
  }
}

const HEADER_AUTOGEN = `<!-- AUTO-GENERATED by scripts/generate_mcp_docs.mjs (E-52) — do not edit by hand. -->
<!-- Run: node scripts/generate_mcp_docs.mjs  (also runs during \`ai sync\`).      -->
<!-- Source of truth: src/config/registry.json + src/mcp/shared/mcp-domains.mjs  -->`;

const DOMAIN_ORDER = [
  "State",
  "Code",
  "Safety",
  "Intelligence",
  "Quality",
  "Interop",
  "Caching",
  "Compute",
];

const MISC_DOMAIN = "Routing & Misc";
const MISC_DESC =
  "Servers that orchestrate other domains (mcp-router) or are not yet categorised. Routing happens here, not inside the listed domains.";

function loadRegistry() {
  const raw = readFileSync(REGISTRY, "utf8");
  return JSON.parse(raw);
}

function describe(_name, def) {
  return _describe(def);
}

function _describe(def) {
  const note = typeof def?._note === "string" ? def._note.trim() : "";
  if (note) {
    const first = note.split(/\.(?:\s|$)/)[0].trim();
    if (first) return first.endsWith(".") ? first : first + ".";
  }
  if (def?.capability) return `${def.capability} server.`;
  return "(no description)";
}

function buildMarkdown(registry) {
  const servers = registry.mcp_servers || {};
  const known = new Set();
  const lines = [];

  lines.push(HEADER_AUTOGEN);
  lines.push("");
  lines.push("# Domain Blueprint: MCP Nervous System");
  lines.push("");
  lines.push("> [!IMPORTANT]");
  lines.push("> This document maps every AI-OS Model Context Protocol (MCP) server, grouped by routing domain. It is generated from `src/config/registry.json` — edit the registry, then re-run the generator. Never edit this file directly.");
  lines.push("");
  lines.push(
    `Total registered servers: **${Object.keys(servers).length}**. The Architect (Gemini) curates DOMAINS; the Engineer (Claude) wires them into the registry.`
  );
  lines.push("");

  for (const domain of DOMAIN_ORDER) {
    const def = DOMAINS[domain];
    if (!def) continue;
    lines.push(`## ${domain}`);
    lines.push(def.description);
    lines.push("");
    for (const serverName of def.servers) {
      const sdef = servers[serverName];
      if (!sdef) {
        lines.push(`- **\`${serverName}\`** — _missing from registry.json_`);
        continue;
      }
      known.add(serverName);
      const cap = sdef.capability || "—";
      lines.push(`- **\`${serverName}\`** (${cap}) — ${describe(serverName, sdef)}`);
    }
    lines.push("");
  }

  // Anything in the registry but not in DOMAINS lands in Routing & Misc.
  const unmapped = Object.keys(servers)
    .filter((n) => !known.has(n))
    .sort();
  if (unmapped.length > 0) {
    lines.push(`## ${MISC_DOMAIN}`);
    lines.push(MISC_DESC);
    lines.push("");
    for (const serverName of unmapped) {
      const sdef = servers[serverName];
      const cap = sdef.capability || "—";
      lines.push(`- **\`${serverName}\`** (${cap}) — ${describe(serverName, sdef)}`);
    }
    lines.push("");
  }

  // Trailing newline matches POSIX file convention.
  return lines.join("\n");
}

function main() {
  const checkMode = process.argv.includes("--check");
  let markdown;
  try {
    if (!REGISTRY) {
      throw new Error(
        `registry.json not found in any of ${REGISTRY_CANDIDATES.join(", ")}`
      );
    }
    const registry = loadRegistry();
    markdown = buildMarkdown(registry);
  } catch (e) {
    // Fail-open: never block sync on a broken registry. Loud on stderr so
    // CI catches it; exit 0 so `ai sync` continues.
    process.stderr.write(
      `[generate_mcp_docs] WARN: ${e.message} — skipping mcp.md regeneration.\n`
    );
    process.exit(0);
  }
  if (checkMode) {
    process.stdout.write(markdown);
    return;
  }
  // Skip silently when CWD has no .ai/blueprints — the project hasn't been
  // initialised. `ai init` creates the directory before the next sync.
  if (!existsSync(join(PROJECT_ROOT, ".ai", "blueprints"))) {
    process.stderr.write(
      `[generate_mcp_docs] WARN: ${PROJECT_ROOT}/.ai/blueprints not found — run \`ai init\` first.\n`
    );
    process.exit(0);
  }
  writeFileSync(TARGET, markdown);
  process.stderr.write(
    `[generate_mcp_docs] wrote ${TARGET} (${markdown.length} bytes)\n`
  );
}

main();
