#!/usr/bin/env node
/**
 * generate_blueprints_index.mjs — auto-generates .ai/blueprints/_INDEX.md (E-110).
 *
 * The hand-curated _INDEX.md silently omitted 20+ domain blueprints, defeating
 * its own "agents MUST consult this index first" contract. This generator
 * rebuilds it as a deterministic manifest of EVERY blueprint (title + Goal
 * one-liner) — modelled on the _SKILLS_INDEX.md generator, with the --check
 * mode of generate_mcp_docs.mjs so a test can diff it against the committed file.
 *
 * Modes:
 *   node scripts/generate_blueprints_index.mjs          → write .ai/blueprints/_INDEX.md
 *   node scripts/generate_blueprints_index.mjs --check  → print to stdout, exit 0
 *
 * Security / robustness:
 *   - No path argument; output is derived from CWD (<project>/.ai/blueprints/).
 *   - Fail-open: any read error logs to stderr and exits 0 so `ai sync` is never
 *     blocked by a malformed blueprint.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

const PROJECT_ROOT = process.cwd();
const BLUEPRINTS_DIR = join(PROJECT_ROOT, ".ai", "blueprints");
const TARGET = join(BLUEPRINTS_DIR, "_INDEX.md");
const SELF = "_INDEX.md"; // never index the index itself

// Extract a one-line Goal from a blueprint body. Prefers the `**Goal**:` line
// under `## Goal & Architecture`; falls back to the first non-empty, non-heading
// line in that section. Returns "" when nothing usable is found.
function extractGoal(text) {
  const lines = text.split("\n");
  const goalLine = lines.find((l) => /^\s*\*\*Goal\*\*\s*:/.test(l));
  if (goalLine) {
    return goalLine.replace(/^\s*\*\*Goal\*\*\s*:\s*/, "").replace(/\*\*/g, "").trim();
  }
  const sectionIdx = lines.findIndex((l) => /^##\s+Goal\b/i.test(l));
  if (sectionIdx !== -1) {
    for (let i = sectionIdx + 1; i < lines.length; i++) {
      const t = lines[i].trim();
      if (t.startsWith("##")) break;
      if (t && !t.startsWith("#")) return t.replace(/^[-*]\s*/, "").replace(/\*\*/g, "").trim();
    }
  }
  return "";
}

// First markdown H1 title, with a leading "Blueprint:" label stripped.
function extractTitle(text, fallback) {
  const m = text.match(/^#\s+(.+)$/m);
  if (!m) return fallback;
  return m[1].replace(/^Blueprint:\s*/i, "").trim() || fallback;
}

function truncate(s, n) {
  return s.length > n ? s.slice(0, n - 1).trimEnd() + "…" : s;
}

function buildMarkdown() {
  const files = readdirSync(BLUEPRINTS_DIR)
    .filter((f) => f.endsWith(".md") && f !== SELF)
    .sort(); // codepoint sort — locale-independent, deterministic across machines

  const lines = [
    "# Blueprints Index (auto-generated — do NOT hand-edit)",
    "",
    "Regenerated by `ai sync` via `scripts/generate_blueprints_index.mjs` (E-110).",
    "Agents: consult this index first (JIT) to find which domain blueprint to load,",
    "then read that file directly. Every `.ai/blueprints/*.md` appears below.",
    "",
  ];
  for (const f of files) {
    let title = f.replace(/\.md$/, "");
    let goal = "";
    try {
      const text = readFileSync(join(BLUEPRINTS_DIR, f), "utf8");
      title = extractTitle(text, title);
      goal = extractGoal(text);
    } catch {
      /* fail-open: list the file even if unreadable */
    }
    lines.push(goal ? `- \`${f}\` — **${title}**: ${truncate(goal, 160)}` : `- \`${f}\` — **${title}**`);
  }
  lines.push("");
  lines.push(`_${files.length} blueprints indexed._`);
  lines.push("");
  return lines.join("\n");
}

function main() {
  const checkMode = process.argv.includes("--check");
  if (!existsSync(BLUEPRINTS_DIR)) {
    process.stderr.write(`[generate_blueprints_index] WARN: ${BLUEPRINTS_DIR} not found — run \`ai init\` first.\n`);
    process.exit(0);
  }
  let markdown;
  try {
    markdown = buildMarkdown();
  } catch (e) {
    process.stderr.write(`[generate_blueprints_index] WARN: ${e.message} — skipping _INDEX.md regeneration.\n`);
    process.exit(0);
  }
  if (checkMode) {
    process.stdout.write(markdown);
    return;
  }
  writeFileSync(TARGET, markdown);
  process.stderr.write(`[generate_blueprints_index] wrote ${TARGET} (${markdown.length} bytes)\n`);
}

main();
